### ISSUE TITLE
Plugin or class not found: "CLI.Refresh_Macros"

### ISSUE THREAD

**Issue by antipa** [fiji/cookbook#7]
I apologize if this is a dumb user error, but I installed the cookbook to test fly F div F0, but I get the error  in the title when I try to execute it on an open image. The other t functions in the cookbook appear to work correctly. I am running on Mac OS 10.14.6 with ImageJ version 2.0.0-rc-69/1.52p.

**Comment by ctrueden** [comment]
Thanks for the bug report, @antipa!

It was a bug in how the script was being packaged. I pushed a commit (14661ee2c536d58f5c28b72f3079d4efab203e91) fixing it, and uploaded a new version of the cookbook to the update site.

It should be functional now. Note that this command is a script, so you can type "F div F0" into the search bar, then click the Source button, to see and edit the script code as well.
